# Generated by Django 5.2.3 on 2026-01-03 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_img', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar Image')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Level')),
                ('xp_current', models.PositiveIntegerField(default=0, verbose_name='Current XP')),
                ('rank', models.CharField(choices=[('E', 'E-Rank'), ('D', 'D-Rank'), ('C', 'C-Rank'), ('B', 'B-Rank'), ('A', 'A-Rank'), ('S', 'S-Rank'), ('SS', 'National Level')], default='E', max_length=10, verbose_name='Rank')),
                ('job_class', models.CharField(default='None', help_text='e.g. Shadow Monarch, Developer, Artist', max_length=50, verbose_name='Job/Class')),
                ('net_worth', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net Worth')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_level', models.PositiveIntegerField(default=1, verbose_name='Physique Level')),
                ('str_xp', models.PositiveIntegerField(default=0, verbose_name='Physique XP')),
                ('int_level', models.PositiveIntegerField(default=1, verbose_name='Intellect Level')),
                ('int_xp', models.PositiveIntegerField(default=0, verbose_name='Intellect XP')),
                ('cha_level', models.PositiveIntegerField(default=1, verbose_name='Charisma Level')),
                ('cha_xp', models.PositiveIntegerField(default=0, verbose_name='Charisma XP')),
                ('wil_level', models.PositiveIntegerField(default=1, verbose_name='Discipline Level')),
                ('wil_xp', models.PositiveIntegerField(default=0, verbose_name='Discipline XP')),
                ('wis_level', models.PositiveIntegerField(default=1, verbose_name='Psyche Level')),
                ('wis_xp', models.PositiveIntegerField(default=0, verbose_name='Psyche XP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='profiles.playerprofile')),
            ],
        ),
    ]
