# Generated by Django 5.2.3 on 2026-01-03 23:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='The date this log belongs to.', verbose_name='Date')),
                ('event', models.CharField(blank=True, max_length=255, null=True, verbose_name='Event / Special Occasion')),
                ('sleep_time', models.TimeField(blank=True, null=True, verbose_name='Last Night Sleep Time')),
                ('wake_up_time', models.TimeField(blank=True, null=True, verbose_name='Wake Up Time')),
                ('nap_duration', models.FloatField(default=0.0, help_text='Duration in hours (e.g. 0.5 for 30 mins)')),
                ('quote', models.TextField(blank=True, null=True, verbose_name='Quote of the Day')),
                ('lesson_of_day', models.TextField(blank=True, null=True, verbose_name='Lesson of the Day')),
                ('positives', models.TextField(blank=True, help_text='What went well today?', null=True, verbose_name='Positive Highlights')),
                ('negatives', models.TextField(blank=True, help_text="What didn't go well?", null=True, verbose_name='Negative Highlights')),
                ('notes_tomorrow', models.TextField(blank=True, null=True, verbose_name='Notes for Tomorrow')),
                ('financial_notes', models.TextField(blank=True, null=True, verbose_name='Financial Notes')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Rate your day from 1 to 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Daily Score')),
                ('emoji', models.CharField(blank=True, help_text='e.g., 😎, 😴, 🚀', max_length=10, null=True, verbose_name='Mood Emoji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Day Page',
                'verbose_name_plural': 'Day Pages',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
