# Generated by Django 5.2.3 on 2026-01-28 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0002_rename_daypage_dailyentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Highlight')),
                ('category', models.CharField(choices=[('POS', 'Positive Highlight'), ('NEG', 'Negative Area to Improve')], max_length=3)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='gate.dailyentry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
