# Generated by Django 5.2.3 on 2026-01-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0003_dailyhighlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyentry',
            name='negatives',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='positives',
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='diary',
            field=models.TextField(blank=True, null=True, verbose_name='Diary / Your Notes'),
        ),
        migrations.AlterField(
            model_name='dailyhighlight',
            name='category',
            field=models.CharField(choices=[('POS', 'Positive Highlight'), ('NEG', 'Negative Area to Improve')], max_length=3, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='dailyhighlight',
            name='content',
            field=models.CharField(blank=True, max_length=255, verbose_name='Highlight'),
        ),
        migrations.AlterField(
            model_name='dailyhighlight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='dailyhighlight',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
