# Generated by Django 5.2.3 on 2026-02-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0004_remove_dailyentry_negatives_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyhighlight',
            index=models.Index(fields=['entry', 'category'], name='gate_dailyh_entry_i_399d0d_idx'),
        ),
    ]
