# Generated by Django 5.2.3 on 2025-12-14 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp_current', models.PositiveIntegerField(default=0)),
                ('rank', models.CharField(choices=[('E', 'E-Rank'), ('D', 'D-Rank'), ('C', 'C-Rank'), ('B', 'B-Rank'), ('A', 'A-Rank'), ('S', 'S-Rank'), ('SS', 'National Level')], default='E', max_length=2)),
                ('job_class', models.CharField(default='None', help_text='e.g. Assassin, Necromancer, Mage', max_length=50)),
                ('strength', models.PositiveIntegerField(default=10, verbose_name='STR')),
                ('agility', models.PositiveIntegerField(default=10, verbose_name='AGI')),
                ('intellect', models.PositiveIntegerField(default=10, verbose_name='INT')),
                ('vitality', models.PositiveIntegerField(default=10, verbose_name='VIT')),
                ('perception', models.PositiveIntegerField(default=10, verbose_name='PER')),
                ('luck', models.PositiveIntegerField(default=10, verbose_name='LUK')),
                ('gold', models.PositiveIntegerField(default=0, help_text='Currency earned from tasks')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
