# Generated by Django 5.2.3 on 2025-12-14 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_playerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='agility',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='intellect',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='luck',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='perception',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='vitality',
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='gold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='job_class',
            field=models.CharField(default='None', help_text='e.g. Shadow Monarch, Developer, Artist', max_length=50),
        ),
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.PositiveIntegerField(default=10)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
