# Generated by Django 5.2.3 on 2026-01-03 23:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('schedule_config', models.JSONField(blank=True, default=dict, verbose_name='Schedule Config')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to archive or hide this routine.', verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='profiles.playerprofile')),
            ],
            options={
                'verbose_name': 'Routine',
                'verbose_name_plural': 'Routines',
                'ordering': ['title'],
                'unique_together': {('profile', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('stat_rewards', models.JSONField(blank=True, default=dict, verbose_name='Stat Rewards')),
                ('duration_minutes', models.PositiveIntegerField(default=15, help_text='The duration estimated amount in minutes.\nNote: Break it into multiple tasks if it is more than 4 hours.', verbose_name='Duration Minutes')),
                ('effort_level', models.PositiveIntegerField(default=1, help_text='Effort level from 1 to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Effort Level')),
                ('impact_level', models.PositiveIntegerField(default=1, help_text='Impact level from 1 to 5.\nNote: 5 will highly affect the calculated rank.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Impact Level')),
                ('fear_factor', models.FloatField(default=1.0, help_text='1.0: Routine (No Fear)\n1.5: Anxiety Inducing\n2.0: High Anxiety or Terrifying', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Fear Factor')),
                ('manual_rank', models.CharField(blank=True, choices=[('E', 'E-Rank'), ('D', 'D-Rank'), ('C', 'C-Rank'), ('B', 'B-Rank'), ('A', 'A-Rank'), ('S', 'S-Rank'), ('SS', 'SS-Rank'), ('Monarch', 'Shadow Monarch')], max_length=10, null=True, verbose_name='Manual Rank')),
                ('computed_rank', models.CharField(choices=[('E', 'E-Rank'), ('D', 'D-Rank'), ('C', 'C-Rank'), ('B', 'B-Rank'), ('A', 'A-Rank'), ('S', 'S-Rank'), ('SS', 'SS-Rank'), ('Monarch', 'Shadow Monarch')], default='E', editable=False, help_text='Automatically computed based on task parameters.', max_length=10, verbose_name='Computed Rank')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed?')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('is_habit', models.BooleanField(default=False, verbose_name='Is Habit?')),
                ('is_routine_item', models.BooleanField(default=False, verbose_name='Is Routine Item?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='profiles.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(blank=True, db_index=True, help_text='Priority order (lower numbers come first). Leave blank to add to the end.', null=True, verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to archive or hide this routine.', verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.routine')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'verbose_name': 'Routine Item',
                'verbose_name_plural': 'Routine Items',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_config', models.JSONField(default=dict)),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Current Streak')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Longest Streak')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habit_config', to='tasks.task')),
            ],
        ),
    ]
