# Generated by Django 5.2.3 on 2026-01-08 13:30

import apps.tasks.models.schedule
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of execution within the routine.')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Description')),
                ('primary_stat', models.CharField(choices=[('STR', 'Physique'), ('INT', 'Intellect'), ('CHA', 'Charisma'), ('WIL', 'Discipline'), ('WIS', 'Psyche')], default='STR', help_text='The main stat this task develops (60% XP or 100% if no secondary).', max_length=3, verbose_name='Primary Stat')),
                ('secondary_stat', models.CharField(blank=True, choices=[('STR', 'Physique'), ('INT', 'Intellect'), ('CHA', 'Charisma'), ('WIL', 'Discipline'), ('WIS', 'Psyche')], help_text='Optional. If set, it receives 40% of the XP.', max_length=3, null=True, verbose_name='Secondary Stat')),
                ('duration_minutes', models.PositiveIntegerField(default=15, help_text='The duration estimated amount in minutes.\nNote: Break it into multiple tasks if it is more than 4 hours.', verbose_name='Duration Minutes')),
                ('effort_level', models.PositiveIntegerField(default=1, help_text='Effort level from 1 to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Effort Level')),
                ('impact_level', models.PositiveIntegerField(default=1, help_text='Impact level from 1 to 5.\nNote: 5 will highly affect the calculated rank.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Impact Level')),
                ('fear_factor', models.FloatField(default=1.0, help_text='1.0: Routine (No Fear)\n1.5: Anxiety Inducing\n2.0: High Anxiety or Terrifying', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Fear Factor')),
                ('manual_rank', models.CharField(blank=True, choices=[('E', 'E-Rank'), ('D', 'D-Rank'), ('C', 'C-Rank'), ('B', 'B-Rank'), ('A', 'A-Rank'), ('S', 'S-Rank'), ('SS', 'SS-Rank'), ('Monarch', 'Shadow Monarch')], max_length=10, null=True, verbose_name='Manual Rank')),
                ('computed_rank', models.CharField(choices=[('E', 'E-Rank'), ('D', 'D-Rank'), ('C', 'C-Rank'), ('B', 'B-Rank'), ('A', 'A-Rank'), ('S', 'S-Rank'), ('SS', 'SS-Rank'), ('Monarch', 'Shadow Monarch')], default='E', editable=False, help_text='Automatically computed based on task parameters.', max_length=10, verbose_name='Computed Rank')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to archive or hide this item.', verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent', models.ForeignKey(blank=True, help_text='If set, this task will be a subtask', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='profiles.playerprofile')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='OneTimeTask',
            fields=[
            ],
            options={
                'verbose_name': 'One-Time Task',
                'verbose_name_plural': 'One-Time Tasks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Completed At')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='XP Earned')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Task Log',
                'verbose_name_plural': 'Task Logs',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='DAILY', max_length=10, verbose_name='Frequency')),
                ('interval', models.PositiveIntegerField(default=1, help_text="e.g.\n1 for 'Every Day/Week/Month/Year',\n2 for 'Every 2 Day/Week/Month/Year'", verbose_name='Repeat Every')),
                ('weekdays', models.JSONField(blank=True, default=apps.tasks.models.schedule.default_weekdays, help_text='Select specific days for Weekly frequency.', verbose_name='On Days')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Current Streak')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Longest Streak')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='tasks.task')),
            ],
        ),
    ]
