# Generated by Django 5.2.3 on 2026-01-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='stat_rewards',
        ),
        migrations.AddField(
            model_name='task',
            name='primary_stat',
            field=models.CharField(choices=[('STR', 'Physique'), ('INT', 'Intellect'), ('CHA', 'Charisma'), ('WIL', 'Discipline'), ('WIS', 'Psyche')], default='STR', help_text='The main stat this task develops (60% XP or 100% if no secondary).', max_length=3, verbose_name='Primary Stat'),
        ),
        migrations.AddField(
            model_name='task',
            name='secondary_stat',
            field=models.CharField(blank=True, choices=[('STR', 'Physique'), ('INT', 'Intellect'), ('CHA', 'Charisma'), ('WIL', 'Discipline'), ('WIS', 'Psyche')], help_text='Optional. If set, it receives 40% of the XP.', max_length=3, null=True, verbose_name='Secondary Stat'),
        ),
    ]
