# Generated by Django 5.2.3 on 2026-02-05 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='completed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Completed At'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['profile', 'is_active', 'parent'], name='tasks_task_profile_08694c_idx'),
        ),
    ]
