# Generated by Django 5.2.3 on 2026-01-04 03:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_stat_rewards_task_primary_stat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='frequency_config',
        ),
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=10, verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='habit',
            name='interval',
            field=models.PositiveIntegerField(default=1, help_text="e.g. 1 for 'Every Day', 2 for 'Every 2 Days'", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Repeat Every'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='time_of_day',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='habit',
            name='weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Select specific days for Weekly frequency (0=Mon, 6=Sun).', verbose_name='On Days'),
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.habit')),
            ],
            options={
                'verbose_name': 'Habit Log',
                'verbose_name_plural': 'Habit Logs',
                'ordering': ['-completed_at'],
            },
        ),
    ]
