# Generated by Django 5.2.3 on 2026-01-04 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_habit_frequency_config_habit_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='schedule_config',
        ),
        migrations.AddField(
            model_name='routine',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=10, verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='routine',
            name='interval',
            field=models.PositiveIntegerField(default=1, help_text="e.g. 1 for 'Every Day', 2 for 'Every 2 Days'", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Repeat Every'),
        ),
        migrations.AddField(
            model_name='routine',
            name='time_of_day',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='routine',
            name='weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Select specific days for Weekly frequency.', verbose_name='On Days'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Select specific days for Weekly frequency (0=Sat, 6=Fri).', verbose_name='On Days'),
        ),
    ]
