# Generated by Django 5.2.3 on 2026-01-04 10:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_routine_schedule_config_routine_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.routineitem')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.routine')),
            ],
            options={
                'verbose_name': 'Routine Log',
                'verbose_name_plural': 'Routine Logs',
                'ordering': ['-completed_at'],
            },
        ),
    ]
