# Generated by Django 5.2.3 on 2026-01-06 11:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_routinelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitlog',
            name='habit',
        ),
        migrations.AlterUniqueTogether(
            name='routine',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='routine',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='routinelog',
            name='routine',
        ),
        migrations.RemoveField(
            model_name='routineitem',
            name='routine',
        ),
        migrations.RemoveField(
            model_name='routineitem',
            name='task',
        ),
        migrations.RemoveField(
            model_name='routinelog',
            name='item',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_habit',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_routine_item',
        ),
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to archive or hide this item.', verbose_name='Is Active?'),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of execution within the routine.'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If set, this task will be a subtask', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task'),
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Task Log',
                'verbose_name_plural': 'Task Logs',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='DAILY', max_length=10, verbose_name='Frequency')),
                ('interval', models.PositiveIntegerField(default=1, help_text="e.g.\n1 for 'Every Day/Week/Month/Year',\n2 for 'Every 2 Day/Week/Month/Year'", verbose_name='Repeat Every')),
                ('weekdays', models.JSONField(blank=True, default=[0, 1, 2, 3, 4, 5, 6], help_text='Select specific days for Weekly frequency.', verbose_name='On Days')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Current Streak')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Longest Streak')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='tasks.task')),
            ],
        ),
        migrations.DeleteModel(
            name='Habit',
        ),
        migrations.DeleteModel(
            name='HabitLog',
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
        migrations.DeleteModel(
            name='RoutineItem',
        ),
        migrations.DeleteModel(
            name='RoutineLog',
        ),
    ]
