# Generated by Django 5.2.3 on 2026-01-07 15:28

import apps.tasks.models.schedule
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_habitlog_habit_alter_routine_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Completed At'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='xp_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='XP Earned'),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='weekdays',
            field=models.JSONField(blank=True, default=apps.tasks.models.schedule.default_weekdays, help_text='Select specific days for Weekly frequency.', verbose_name='On Days'),
        ),
    ]
