# Generated by Django 5.2.3 on 2026-01-07 17:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tasklog_completed_at_alter_tasklog_xp_earned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='OneTimeTask',
            fields=[
            ],
            options={
                'verbose_name': 'One-Time Task',
                'verbose_name_plural': 'One-Time Tasks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.task',),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
    ]
