# Generated by Django 5.2.3 on 2026-01-07 18:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_habit_onetimetask_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description'),
        ),
    ]
