# Generated by Django 5.2.3 on 2025-11-18 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Morning Routine', 'Workout', 'Evening Wind-down'", max_length=100, verbose_name='Routine Name')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to archive or hide this routine.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Routine',
                'verbose_name_plural': 'Routines',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RoutineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="What is the routine item? (e.g., 'Brushing Teeth', 'Meditate 10 mins')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Any extra details about the item (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('priority', models.PositiveIntegerField(blank=True, help_text='Priority order (lower numbers come first). Leave blank to add to the end.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_items', to='daily.routine')),
            ],
            options={
                'verbose_name': 'Routine Item',
                'verbose_name_plural': 'Routine Items',
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
