# Generated by Django 5.2.3 on 2025-12-14 12:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineitem',
            name='description',
            field=models.TextField(blank=True, help_text='Any extra details about the item (optional)', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='routineitem',
            name='priority',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Priority order (lower numbers come first). Leave blank to add to the end.', null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='routineitem',
            name='title',
            field=models.CharField(help_text="What is the routine item? (e.g., 'Brushing Teeth', 'Meditate 10 mins')", max_length=255, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='DayPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='The date this log belongs to.', verbose_name='Date')),
                ('event', models.CharField(blank=True, max_length=255, null=True, verbose_name='Event / Special Occasion')),
                ('wake_up_time', models.TimeField(blank=True, null=True, verbose_name='Wake Up Time')),
                ('sleep_time', models.TimeField(blank=True, null=True, verbose_name='Sleep Time')),
                ('quote', models.TextField(blank=True, null=True, verbose_name='Quote of the Day')),
                ('lesson_of_day', models.TextField(blank=True, null=True, verbose_name='Lesson of the Day')),
                ('positives', models.TextField(blank=True, help_text='What went well today?', null=True, verbose_name='Positive Highlights')),
                ('negatives', models.TextField(blank=True, help_text="What didn't go well?", null=True, verbose_name='Negative Highlights')),
                ('notes_tomorrow', models.TextField(blank=True, null=True, verbose_name='Notes for Tomorrow')),
                ('financial_notes', models.TextField(blank=True, null=True, verbose_name='Financial Notes')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Rate your day from 1 to 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Daily Score')),
                ('emoji', models.CharField(blank=True, help_text='e.g., 😎, 😴, 🚀', max_length=10, null=True, verbose_name='Mood Emoji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Day Page',
                'verbose_name_plural': 'Day Pages',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
