# Generated by Django 5.2.3 on 2025-12-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_alter_routineitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daypage',
            name='sleep_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Last Night Sleep Time'),
        ),
    ]
