# Generated by Django 5.2.3 on 2025-12-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_alter_daypage_sleep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='daypage',
            name='nap_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Nap Time'),
        ),
    ]
