# Generated by Django 5.2.3 on 2025-12-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_daypage_nap_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daypage',
            name='nap_time',
        ),
        migrations.AddField(
            model_name='daypage',
            name='nap_duration',
            field=models.FloatField(default=0.0, help_text='Duration in hours (e.g. 0.5 for 30 mins)'),
        ),
    ]
